services:
  - type: web
    name: library-api--Lab5
    env: docker
    repo: https://github.com/varinskaevg/NUPP_NET_2025_302_TK_Varinska__Lab
    branch: Lab5
    dockerfilePath: Dockerfile
    plan: free
