services:
  - type: web
    name: library-api--Varinska
    runtime: dotnet
    branch: Lab5
    buildCommand: dotnet publish LibraryREST/LibraryREST.csproj -c Release -o out
    startCommand: dotnet out/LibraryREST.dll
    buildFilter:
      paths:
        - "**/*"
